<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>Title</title>
</head>
<body>
    <h1>Eptituders</h1>
    <table>
        <tr>
            <th>Name</th>
            <th>Side</th>
            <th>Clan</th>
        </tr>
        <tr>
            <td>${eptituder.name}</td>
            <td>${eptituder.side}</td>
            <td>${eptituder.clan.name}</td>
        </tr>
    </table>
</body>
</html>
